# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: CTA
  description: 
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content_width: Large
  content_alignment: Left
  vertical_alignment: Top
  blocks:
    - bookshop:structure:simple_blocks!(headline)
    - bookshop:structure:simple_blocks!(button)

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  blocks: 
    - _bookshop_name: headline
      text: BookShop Starter Library ipsum dolo sitor orciarius nato quntess, nas cheturo ridicu lusos mus.
      heading_level: h2
    - _bookshop_name: button
      text: Learn more
      disabled: false
      url: /
      open_in_new_tab: false
      style: Primary
      size: Responsive

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: select
    options:
      values:
        - Small
        - Medium
        - Large
  content_alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right
  vertical_alignment:
    type: select
    options:
      values:
        - Top
        - Middle
        - Bottom