# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - simple_blocks
  label: List
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  list_items: [bookshop:cloudcannon/paragraph]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  list_items:
    - bookshop:cloudcannon/paragraph
    - bookshop:cloudcannon/paragraph
    - bookshop:cloudcannon/paragraph

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: