# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Accordian
  description: 
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content_width: Full
  content_alignment: Center
  accordians:
    - heading:
      content:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  accordians:
    - heading: BookShop Starter Library 
      content: Duis accumsan mauris dui, a eleifend massa maximus eu. Aliquam a rhoncus dolor. In enim lectus, cursus sed auctor gravida, gravida nec justo. Quisque lacinia, lectus eget efficitur commodo, magna nulla efficitur elit, eget lacinia ligula quam at ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris sed tempus odio, vel malesuada enim. Donec aliquet at lectus eget accumsan
    - heading: BookShop Starter Library 
      content: Duis accumsan mauris dui, a eleifend massa maximus eu. Aliquam a rhoncus dolor. In enim lectus, cursus sed auctor gravida, gravida nec justo. Quisque lacinia, lectus eget efficitur commodo, magna nulla efficitur elit, eget lacinia ligula quam at ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris sed tempus odio, vel malesuada enim. Donec aliquet at lectus eget accumsan
    - heading: BookShop Starter Library 
      content: Duis accumsan mauris dui, a eleifend massa maximus eu. Aliquam a rhoncus dolor. In enim lectus, cursus sed auctor gravida, gravida nec justo. Quisque lacinia, lectus eget efficitur commodo, magna nulla efficitur elit, eget lacinia ligula quam at ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris sed tempus odio, vel malesuada enim. Donec aliquet at lectus eget accumsan

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: select
    options:
      values:
        - Full
        - Half
  content_alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right