# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
    - content_blocks
  label: Spacer
  description: Spacer for between components
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    height: 120

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  height:
    type: range
    options:
      step: 1
      max: 200
      min: 40