# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "Two column header"
  description: CTA column and image column
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image_alignment: Left
  image:
    path: ""
    alt: ""
  cta_block:
    cta: bookshop:cta
    text_color: Primary
    background_color:
      white: true
      color: "#F0F0F0"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: 
    path: http://placekitten.com/580/300
    alt: Image alt

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_alignment:
    type: select
    options:
      values:
        - Left
        - Right
  text_color:
    type: select
    options:
      values:
        - Primary
        - Secondary
  white:
    type: checkbox
  color:
    type: color
    hidden: "!white"
