# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "Two Columns"
  description:
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    left_column:
      style:
        content_alignment: Left
        vertical_alignment: Top
        custom_background_color: false
        background_color: '#f5f5f5'
      content:
        blocks:
          - bookshop:structure:content_blocks
    right_column:
      style:
        content_alignment: Left
        vertical_alignment: Top
        custom_background_color: false
        background_color: '#f5f5f5'
      content:
        blocks:
          - bookshop:structure:content_blocks
  style:
    gap: 40

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  gap:
    type: range
    options:
      min: 5
      max: 200
      step: 1
  vertical_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_vertical_top
          name: Top
        - icon: align_vertical_center
          name: Middle
        - icon: align_vertical_bottom
          name: Bottom
  content_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_horizontal_left
          name: Left
        - icon: align_horizontal_center
          name: Center
        - icon: align_horizontal_right
          name: Right
  custom_background_color:
    type: switch
  background_color:
    type: color
    hidden: "custom_background_color"