# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: CTA
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    content_width: Large
    content_alignment: Left
    vertical_alignment: Top
  content:
    blocks:
      - bookshop:structure:simple_blocks!(cloudcannon/simple/headline)
      - bookshop:structure:simple_blocks!(cloudcannon/simple/button)

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    blocks:
      - _bookshop_name: cloudcannon/simple/headline
        text: BookShop Starter Library ipsum dolo sitor orciarius nato quntess, nas cheturo ridicu lusos mus.
        heading_level: h2
      - _bookshop_name: cloudcannon/simple/button
        text: Learn more
        disabled: false
        url: /
        open_in_new_tab: false
        style: Primary
        size: Responsive

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: choice
    options:
      values:
        - name: Small
          icon: width_normal
        - name: Medium
          icon: width_wide
        - name: Large
          icon: rectangle
  vertical_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_vertical_top
          name: Top
        - icon: align_vertical_center
          name: Middle
        - icon: align_vertical_bottom
          name: Bottom