# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: Hero image
  description: Hero image that spans the page
  icon: panorama
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    content_width: Large
    content_alignment: Center
  content:
    path: ""
    alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    image:
      path: http://placekitten.com/580/300
      alt: Image alt

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: choice
    options:
      values:
        - name: Small
          icon: width_normal
        - name: Medium
          icon: width_wide
        - name: Large
          icon: rectangle
  path:
    type: image
