# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - simple_blocks
  label: Input CTA
  description: Form CTA with configurable input field
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:headline
  paragraph: bookshop:paragraph
  input: bookshop:input
  button:
    default_value: Button
    name: button
    _input_type: submit
    url: ""
    style: Primary
  content_width: Medium
  content_alignment: Left

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: select
    options:
      values:
        - Small
        - Medium
        - Large
  content_alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right