# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Accordion
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    content_width: Full
    content_alignment: Center
  content:
    accordions:
      - heading:
        content: bookshop:cloudcannon/paragraph

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    accordions:
      - heading: BookShop Starter Library
        content: bookshop:cloudcannon/paragraph
      - heading: BookShop Starter Library
        content: bookshop:cloudcannon/paragraph
      - heading: BookShop Starter Library
        content: bookshop:cloudcannon/paragraph

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: select
    options:
      values:
        - Full
        - Half
  content_alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right