# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - simple_blocks
  label: Quote
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  quote: Quote text
  source: Quote source
  content_width: Medium
  content_alignment: Left

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  quote: >-
    Orci varius natoque penatibus et magnis dis parturient montes,
    nascetur ridiculus mus. Mauris sed tempus odio, vel malesuada enim.
    Donec aliquet at lectus eget accumsan

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  quote:
    type: textarea
  content_width:
    type: select
    options:
      values:
        - Small
        - Medium
        - Large
  content_alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right
