# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "FAQ"
  description: "Heading with a list of collapsible accordions"
  icon: question_answer
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    content_alignment: Center
    content_width: Large
    borders: true
    custom_background_color: false
    background_color: '#f5f5f5'
  content:
    heading: "Frequently asked questions"
    items:
      - bookshop:cloudcannon/accordion

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: choice
    options:
      values:
        - name: Small
          icon: width_normal
        - name: Medium
          icon: width_wide
        - name: Large
          icon: rectangle
  borders:
    type: switch
  border-color:
    hidden: "borders"
  custom_background_color:
    type: switch
  background_color:
    hidden: "custom_background_color"

