# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "Logo ticker"
  description: Show off some of the big names associated with your product
  icon: collections
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    height: 45
  content:
    logos:
      - image:
        alt:
        link:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  style:
    height: 45
  content:
    logos:
      - image: http://placekitten.com/580/300
        alt: Logo alt
        link: '/'

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  height:
    type: range
    options:
      step: 1
      min: 20
      max: 100
  alt:
    type: text