# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - simple_blocks
  label: Line
  description: Line
  icon: horizontal_rule
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  style:
    content_width: Large

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: choice
    options:
      values:
        - name: Small
          icon: width_normal
        - name: Medium
          icon: width_wide
        - name: Large
          icon: rectangle
