# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - simple_blocks
  label: Input CTA
  description: Form CTA with configurable input field
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:cloudcannon/simple/headline
    paragraph: bookshop:cloudcannon/simple/paragraph
    input: bookshop:cloudcannon/simple/input
    button:
      default_value: Button
      name: button
      input_type: submit
      url: ""
      style: Primary
  style:
    content_width: Medium
    content_alignment: Left

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: choice
    options:
      values:
        - name: Small
          icon: width_normal
        - name: Medium
          icon: width_wide
        - name: Large
          icon: rectangle
  content_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_horizontal_left
          name: Left
        - icon: align_horizontal_center
          name: Center
        - icon: align_horizontal_right
          name: Right