# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "Two Columns"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content_width: Large
  content_alignment: Left
  left_column: [bookshop:structure:content_blocks]
  right_column: [bookshop:structure:content_blocks]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_width:
    type: select
    options:
      values:
        - Small
        - Medium
        - Large
  content_alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right
