# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "Two Columns"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  left_column: [bookshop:structure:content_blocks]
  right_column: [bookshop:structure:content_blocks]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  left_column: 
    - bookshop:cta-with-background
  right_column:
    - bookshop:cta-with-background

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
