# Metadata about this component, to be used in the CMS
spec:
  structures:
    - sections
  label: "Custom"
  description: An empty section that can be customized to your needs
  icon: edit_note
  tags: []
  text_key: "section_name"

# Defines the structure of this component, as well as the default values
blueprint:
  section_name: My section
  include_background_color: false
  background_color: "#F0F0F0"
  include_background_image: false
  background_image_path:
  content_blocks: bookshop:cloudcannon/structural/content_blocks

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color:
    type: color
    options:
      format: rgb
      alpha: true
  include_background_color:
    type: switch
  background_color:
    type: color
    hidden: "include_background_color"
  include_background_image:
    type: switch
  background_image_path:
    type: image
    hidden: "include_background_image"
  include_background_overlay:
    type: switch
  background_overlay:
    hidden: "include_background_overlay"
  curved_edges:
    type: switch