# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Iframe embed
  description:
  icon: code
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    url: https://player.vimeo.com/video/622005181?h=cf41e0814a&app_id=122963

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  url:
    type: url
